### ISSUE TITLE
Unsucessfully Installation the Plugin

### ISSUE THREAD

**Issue by jeevanganesh** [danioxoli/HotSpotAnalysis_Plugin#51]
I have been trying unsuccessfully to get this plugin working on a Windows machine running QGIS 3.2.3 that was installed through OSGeo4W. I followed the instructions to upgrade pip and install pysal but I am receiving the following error in the QGIS Python log when I try to initiate the plugin:

Couldn't load plugin 'HotspotAnalysis' due to an error when calling its classFactory() method 

AttributeError: module 'pysal' has no attribute 'core' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 38, in 
    import pysal
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pysal\__init__.py", line 53, in 
    open = pysal.core.FileIO.FileIO
AttributeError: module 'pysal' has no attribute 'core'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.1-București București, 121cc00ff0 

Python Path:
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BoundaryDelineation/lib
C:/OSGEO4~1/apps/qgis/./python
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGEO4~1\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGEO4~1\bin
C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
.
Kindly help me Install Hotspot Analysis Plugin
Email id  jeevanganesh@rediffmail.com
Best Regards,
M.Ganesan

**Comment by danioxoli** [comment]
Please try again the installation of the PySAL library requested by your plugin version. It looks like you are working with PySAL 2 instead of PySAL 1.14. However, you could also try the dev version of the plugin that supports PySAL 2 (see https://github.com/danioxoli/HotSpotAnalysis_Plugin/tree/qgis3pysal2)
